# Generated by Django 2.2.4 on 2019-08-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1024, verbose_name='first name')),
                ('last_name', models.CharField(max_length=1024, verbose_name='last name')),
                ('member_since', models.DateField(auto_now_add=True, verbose_name='member since')),
            ],
        ),
    ]
